language: go
sudo: false

go:
  - go1.5
  - go1.6
  - go1.7
  - go1.8
  - tip

before_install:
  - go get -t -v ./...

script:
  - ./.travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
